### ISSUE TITLE
Update Icons?

### ISSUE THREAD

**Issue by lauraerinmann** [tdg5/font-awesome-bower#6]
I noticed some of the current icons provided by font awesome are missing, for example: icon-circle-blank is not included.  How are you selecting what icons to maintain?  How can I help update this library?  Thanks!!!

**Comment by stefanbirkner** [comment]
`icon-circle-blank` is an icon name of Font Awesome 3.x. It has changed to `circle-o` in Font Awesome 4.x (see [Upgrading from 3.2.1 to 4](https://github.com/FortAwesome/Font-Awesome/wiki/Upgrading-from-3.2.1-to-4)). We are only providing Font Awesome 4.x.
